Made tests for the project
mnaibei/math-magicians pull request #6
Opened 2023-05-01 15:17 UTC by mnaibei

- Used jest testing library to make tests for math-magicians app
- Checked linters
- Created PR

2023-05-01 15:21 UTC, DammyShittu commented
Hi @mnaibei,

While you made a great effort in this project, I cannot proceed to review your code.

## Invalid Code Review Request

### Ensure you collaborate with your coding partner.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-03 09:27 UTC, danmainah requested changes
Hi @mnaibei and @RHK-MICROVERSE , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ All tests are passing 
✔️ Gitflow was correctly used
✔️  Good design


# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- [ ] @team great work testing your application, while running the app I discovered your quotes are not loading , it would be nice if you fixed the error causing this problem
![image](https://user-images.githubusercontent.com/61408860/235879650-0c6ebb6b-9da3-454b-9359-7096c62bdf23.png)


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-05-03 09:27 UTC, danmainah commented on src/test/calcLogic.test.js
> +});
- [ ] @mnaibei and @RHK-MICROVERSE great work on your tests, however, you didn't cover all functionalities and scenarios while testing the `operate.js` and `calculate.js` modules.

For instance, in the calculate.js file the if statement shown below represents a scenario, the same case applies to the operate.js file
![image](https://user-images.githubusercontent.com/61408860/235878460-b200022f-b53b-448f-b995-f25ef0dcef09.png)

- [ ] @team While you did a great job testing the components you forgot to add tests for Navbar and Display components, kindly consider adding tests for these components as it was part of the project requirement as shwon below

![image](https://user-images.githubusercontent.com/61408860/235879278-d9d8af74-8e1a-4cb1-894c-51cedbb6ac94.png)

2023-05-03 09:31 UTC, mnaibei commented on src/test/calcLogic.test.js
> +});
@danmainah the quotes are not working because I have hidden the API key from github

2023-05-03 11:00 UTC, uwadonat approved these changes
## Hi @mnaibei,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 
### Highlights
- Good project structure ✔️
- Professional readme file ✔️
- No linter errors ✔️
- Amazing design ✔️
![thanks-awesome](https://user-images.githubusercontent.com/65860678/235898103-be88a989-8059-4ac4-bce7-fa4f222bd878.gif)

# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-05-03 11:01 UTC, merged